### ISSUE TITLE
Problem with encoding in searches

### ISSUE THREAD

**Issue by patxoca** [hrs/engine-mode#10]
First at all, very useful mode!! Thanks!!

I'm having some trouble searching for non ASCII content on the *Institut d'Estudis Catalans*:

```lisp
(defengine diec2
  "http://dlc.iec.cat/results.asp?txtEntrada=%s"
  "c")
```

If I `C-x / c força RET` the DIEC engine searches for `forã§a` and displays no result. Converting manually the text to latin1 and pasting the quoted result into the URL (`for%E7a`) works.

Maybe `defengine` could accept an optional argument in order to specify either a target encoding or a transformation function?

**Comment by hrs** [comment]
This has been resolved in #16, so I'm gonna close it. Thanks for the suggestion!
