### ISSUE TITLE
Rebinding C-c /

### ISSUE THREAD

**Issue by Xparx** [hrs/engine-mode#12]
Hi,
This might be a noob question, but I'm having huge issues trying to rebind the default prefix command.

what I have tried:

    (setq engine/keymap-prefix "C-c s")

    (custom-set-variables '(engine/keymap-prefix (kbd "C-c s")))

and both of the above with 

    (put engine/keymap-prefix 'customized-value (list (custom-quote (eval engine/keymap-prefix))))

I have also tried to use the customize interface and set the value but nothing seems to make the value stick to what I assign to it (engine/keymap-prefix)

I'm obviously missing something here but even looking at how to make defcustom variable changes stick in the emacs (help section)[http://www.emacswiki.org/emacs/CustomizingAndSaving#toc4] I can not make sense of it.
What am I doing wrong?

**Comment by hrs** [comment]
Hi, @Xparx! Sorry about the slow reply (we've been moving house), but I think I have a solution for you.

I think your intuition was right: the first thing you tried—`(setq engine/keymap-prefix "C-c s")`—was *almost* right, but you'll need to use `kbd` to translate the string `"C-c s"` into Emacs' internal key representation.

Instead, try:
```lisp
(setq engine/keymap-prefix (kbd "C-c s"))
```
Let me know if that works for you. I'll add a note in the README if it does!

**Comment by Xparx** [comment]
Hi, Thanks for your reply!
I apply your suggestion but
there seems to be some underlying issue here that I don't understand.
The key combination is registered as changed if I run 

    C-h v engine/keymap-prefix

It sais this variable is changed

    Its value is "^Cs"
    Original value was "^C/"

however now if I do 

    C-h f engine/search-duckduckgo

I get the message

    It is bound to C-c / d.

It seems to me that the prefix argument doesn't change the search command for some reason.

**Comment by hrs** [comment]
Ah, OK, that makes sense, since changing the prefix argument doesn't change the bindings and engines that have already been defined.

If you change the prefix, and *then* define an engine with `defengine`, does that work?

**Comment by Xparx** [comment]
Yes that worked! 
Ok, so I'll define the prefix before defengine and I should be alright. 
Thanks for the help.

**Comment by hrs** [comment]
Great! I just added some documentation to the README  about this (in https://github.com/hrs/engine-mode/commit/fac252e11dd38fe89d6285a12352fee0e4d31b00), so I'm gonna close this issue. Thanks!
