### ISSUE TITLE
Where are `defengine` s added to engine-mode.el?

### ISSUE THREAD

**Issue by SeaDude** [hrs/engine-mode#31]
Hello, 

I can't seem to figure out where your list of `defengine`s is added to the `engine-mode.el` file. I pasted them in after `defmacro defengine` but that didn't seem to work.

For some reason the keybinding ` C-x / ` is undefined as well. I feel like I didn't install correctly or something. 

Installation: 

- M-x install-packages
- engine-mode
- added `(require 'engine-mode) (engine-mode t)` to my `config.org` file

Any ideas? 

Thanks!

**Comment by hrs** [comment]
Hmm, it sounds like you're adding the `defengine` declarations to `engine-mode.el`? If so, that's not quite right. You'll want to leave `engine-mode.el` unchanged and add those declarations in your config file instead.

For reference, here's [my engine-mode config](https://github.com/hrs/dotfiles/blob/master/emacs.d/configuration.org#add-a-bunch-of-engines-for-engine-mode).

I hope that helps! Let me know if there's anything else I can do.

**Comment by SeaDude** [comment]
Thanks for the clarification. I added the declarations to my `config.org` file and can now search from Emacs.
