### ISSUE TITLE
Missing dependency on format-spec

### ISSUE THREAD

**Issue by endgame** [hrs/engine-mode#42]
If I have a minimal emacs installation, and I install `engine-mode`, then when I try to use engine commands, I get the error
```
engine/execute-search: Symbol’s function definition is void: format-spec-make
```
A simple fix is to stick a `(require 'format-spec)` somewhere but I don't know if that's correct w.r.t. the magic comments for the packaging system (`format-spec` appears to come built-in with emacs).

A workaround for users: add a `(require 'format-spec)` to the `use-package` call that pulls it in:
```elisp
(use-package engine-mode
  :config
  (require 'format-spec)
  (engine-mode t)
  ;; Other setup
  )
```

**Comment by phil-s** [comment]
This is a legitimate bug with a trivial fix -- simply change this:

    (eval-when-compile (require 'cl-macs))

to this:

    (eval-when-compile (require 'cl-macs))
    (require 'format-spec)

Noting that we definitely want `(require 'format-spec)` outside of the `eval-when-compile`, as that is only wanted for macro usage.

**Comment by hrs** [comment]
That's true. I ought to have done this a long time ago; sorry about that!

I've just included that dependency and released a new version. I hope that helps!
