### ISSUE TITLE
Potential breakage when re-using properties for default input

### ISSUE THREAD

**Issue by Ambrevar** [hrs/engine-mode#43]
When point is on a thing that has a local keymap property, the local keymap is transfered to the prompt when prompting the initial value.  This can potentially break engine.el.

Example recipe:

```lisp
(defun break-message ()
  (error "broken"))

(defun break ()
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "<return>") 'break-message)
    (add-text-properties
     (point-min) (+ 10 (point-min))
     `(local-map ,map))))
```

Now call the above in a buffer that starts with `foo bar`, place the point on foo, call on engine search and press `M-n`.  From there, you won't be able to press enter.

An easy fix:

```diff
-  (let ((current-word (or (thing-at-point 'symbol) "")))
+  (let ((current-word (or (thing-at-point 'symbol 'no-properties) "")))
```

**Comment by Ambrevar** [comment]
Friendly ping! :) @hrs

**Comment by hrs** [comment]
Thanks very much, @Ambrevar, and sorry about the slow reply. I've merged in your suggested change.

That's a heck of a subtle bug; nice catch! :smiley:
