### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by Ambrevar** [hrs/engine-mode#45]
With the recent fix, what about bumping the version to 2.1.1?
By the way, the 2.1.0 tag is missing.

Cheers!

**Comment by hrs** [comment]
Whoops, good point! I've just bumped the version number in https://github.com/hrs/engine-mode/commit/96b3488a6de2f50b8ba3a101e04ebcbe9821a989 and pushed a `v2.1.1` tag (along with the old `v2.1.0`). Thanks for the reminder!
