### ISSUE TITLE
Feature request to keep log what keyword that have been searched

### ISSUE THREAD

**Issue by Moanrisy** [hrs/engine-mode#49]
I'm imagining I can track all of my search engine usage with org-mode.

Each time I use engine-mode to browse something, it will log 
- time
- engine-mode that used (youtube / duckduckgo / amazon /etc)
- keyword

If I have log like that, I can track how much thing that I have been searched, I can schedule what keyword need to be search again (maybe yearly with org-schedule)

**Comment by Hugo-Heagren** [comment]
I'd like to add my support for this, but as interactive history, which could be used for completion when searching, just like history in browser-based search engines.

**Comment by hrs** [comment]
Thanks for the idea, and sorry for the ridiculously slow reply!

However, I think this is a bit too far outside of the scope of `engine-mode`, so I'm going to close the issue.

If you'd like to build something like this for your personal use, though, you might try doing it using Emacs Lisp's [advice](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html) functionality, which works a bit like decorators in other languages.

```emacs
(defun log-search-term (engine-url browser-function search-term)
  (append-to-file (format "%s\n" search-term)
                  nil
                  "~/saved-searches.txt")
  (list engine-url browser-function search-term))

(advice-add 'engine/execute-search :before #'log-search-term)
```

In this example the `log-search-term` function takes the arguments sent to `engine/execute-search`, appends the search term to a file, and returns the arguments, passing them along to `engine/execute-search` which then evaluates as usual.

Here we're just appending the term to a plain text file, but you could put arbitrarily complex logic in there, maybe to construct an org entry with an associated timestamp.
