### ISSUE TITLE
not a valid key definition; see ‘key-valid-p’

### ISSUE THREAD

**Issue by morgandavidson** [hrs/engine-mode#59]
Hello, thank you for this great mode!

My config is:

```elisp
(use-package engine-mode
  :config 
  (engine-mode t)
  :bind
  (:map org-mode-map ("C-k" . nil))
  :bind-keymap
  ("C-k" . engine-mode-prefixed-map)
  )
````

I have to define many engines, so I use 3 letters to bind them, e.g.:

```elisp
  (defengine IMDB
    "http://www.imdb.com/find?s=all&q=%s"
    :keybinding "imd")
```

Since `engine-mode` latest update, when the engine binding is >1 letter, I have the following error message:  `keymap--check: "imd" is not a valid key definition; see ‘key-valid-p’`

**Comment by hrs** [comment]
Interesting! I'm using Emacs 30, and `"imd"` seems to be a valid keybinding there. Before I figure out how to simultaneously install 29, too :sweat_smile:, could you let me know if putting spaces in the binding (like `"i m d"` instead of `"imd"`) works?

**Comment by morgandavidson** [comment]
My bad, it is not related to Emacs 29 but to `engine-mode` latest update (1 month ago, or so). I updated the post. Spacing the letters seems to work, thank you!

**Comment by hrs** [comment]
Oh, cool, good to hear! I'll close this issue.

**Comment by morgandavidson** [comment]
I updated my 50+ `defengine`, and everything works fine.
```
#+name: search-engines
|---------------------+-----------------------------------------------------------------------------+-----+-----|
| Name                | URL                                                                         | key | Cat |
|---------------------+-----------------------------------------------------------------------------+-----+-----|
| IMDB                | http://www.imdb.com/find?s=all&q=%s                                         | imd | db  |
...
```
```python
#+begin_src python :var tbl=search-engines :results output drawer
  for row in tbl[1:]:
	print(f'(defengine {row[0]}\n  "{row[1]}"\n  :keybinding "{" ".join(row[2])}")')
#+end_src
```
