### ISSUE TITLE
Allow the browser function to be specified per engine

### ISSUE THREAD

**Issue by phil-s** [hrs/engine-mode#9]
I think primarily this would be useful for choosing eww (or similar) for particular search types, if your default browser is external.

Some web pages are pretty awful to use in anything other than one of the major web browsers, but OTOH eww is quite astoundingly convenient for sufficiently basic pages.

An extra optional argument to defengine for this would be handy.

**Comment by hrs** [comment]
@phil-s I totally agree! That's a good idea. I've got an implementation sitting in #18... feel free to take a look and/or comment, and I'll probably merge it in after a day or two.

**Comment by hrs** [comment]
Fixed in https://github.com/hrs/engine-mode/commit/2c327f178598a41c753b3e3a5b3bc9d4d064fe2a. Thanks again for the suggestion!
